### ISSUE TITLE
[BUG] Reading Request body with wrong way

### ISSUE THREAD

**Issue by ramin-guliyev** [TechBuddyTR/TechBuddy.Extensions#22]
Hi all, I am very happy for being first issuer for this awesome project :)

I get an issue when try to use ValidationExtension.Tests.AF with correct informations. Error says that Cannot access a disposed object. 

![console](https://user-images.githubusercontent.com/66221277/203832970-cc228b72-9898-4f89-be4f-357691a9c918.PNG)

I guess error happen when try to read body stream 2 or more time. Body is a stream, when you read it first time you can't read again because its position. Reader method is below:

![reader](https://user-images.githubusercontent.com/66221277/203833433-8c072671-cffb-4f32-9a7a-51b606552180.PNG)

Also I add azure function body screenshot here.

![func2](https://user-images.githubusercontent.com/66221277/203833617-2016dba5-605b-45bd-a555-06ecc467a673.PNG)

**Comment by salihcantekin** [comment]
Thanks for letting us know about this bug. There has been a fix deployed for this issue. Please see the PR for the details

**Comment by salihcantekin** [comment]
new release published which means the new nuget package is deployed as well.
